controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    cartesian_impedance_controller:
      type: impedance_controller/ImpedanceController

impedance_controller:
  ros_parameters:
    translational_stiffness:
      150.0
    rotational_stiffness:
      10.0